### ISSUE TITLE
build failure against cereal-0.3.0.0

### ISSUE THREAD

**Issue by pheaver** [vincenthz/hs-socks#2]
I get the following error when building against cereal-0.3.0.0. It works with cereal-0.3.5.2. Looks like socks needs a version constraint on cereal.

Network/Socks5/Command.hs:79:46: Not in scope: `runGetPartial'

Network/Socks5/Command.hs:80:12:
    Not in scope: data constructor `Fail'

Network/Socks5/Command.hs:81:12:
    Not in scope: data constructor `Partial'

Network/Socks5/Command.hs:82:12:
    Not in scope: data constructor `Done'
